[package]
name = "vulkan-tuto-ash"
version = "0.0.1"
edition = "2024"
authors = ["eldenhell"]
publish = false

[dependencies]
winit = { version = "0.30", features = ["rwh_06"] }
ash = "0.38"
ash-window = "0.13"
num = "0.4.3"
glam = "0.33.5"

[[bin]]
name = "00"
path = "src/tutorials/triangle/00_base_code.rs"
[[bin]]
name = "01"
path = "src/tutorials/triangle/01_instance_creation.rs"
[[bin]]
name = "02"
path = "src/tutorials/triangle/02_validation_layers.rs"
[[bin]]
name = "03"
path = "src/tutorials/triangle/03_physical_device.rs"
[[bin]]
name = "04"
path = "src/tutorials/triangle/04_logical_device.rs"
[[bin]]
name = "05"
path = "src/tutorials/triangle/05_window_surface.rs"
[[bin]]
name = "06"
path = "src/tutorials/triangle/06_swap_chain_creation.rs"
[[bin]]
name = "07"
path = "src/tutorials/triangle/07_image_views.rs"
[[bin]]
name = "08"
path = "src/tutorials/triangle/08_shader_modules.rs"
[[bin]]
name = "09"
path = "src/tutorials/triangle/09_fixed_functions.rs"
[[bin]]
name = "10"
path = "src/tutorials/triangle/10_graphic_pipeline.rs"
[[bin]]
name = "11"
path = "src/tutorials/triangle/11_command_buffers.rs"
[[bin]]
name = "12"
path = "src/tutorials/triangle/12_rendering_and_presentation.rs"
[[bin]]
name = "13"
path = "src/tutorials/triangle/13_frames_in_flight.rs"
[[bin]]
name = "14"
path = "src/tutorials/triangle/14_recreate_swapchain.rs"
[[bin]]
name = "15"
path = "src/tutorials/vertex_buffer/15_input_description.rs"
[[bin]]
name = "16"
path = "src/tutorials/vertex_buffer/16_buffer_creation.rs"
[[bin]]
name = "17"
path = "src/tutorials/vertex_buffer/17_staging_buffer.rs"
[[bin]]
name = "18"
path = "src/tutorials/vertex_buffer/18_index_buffer.rs"
[[bin]]
name = "19"
path = "src/tutorials/uniform_buffer/19_descriptor_layout_and_buffer.rs"

[workspace.lints.clippy]
# https://rust-lang.github.io/rust-clippy/master/index.html
type_complexity = "warn"
doc_markdown = "warn"
manual_let_else = "warn"
match_same_arms = "warn"
redundant_else = "warn"
semicolon_if_nothing_returned = "warn"
nonstandard_macro_braces = "warn"

# restriction
as_pointer_underscore = "warn"
as_underscore = "warn"
cfg_not_test = "warn"
clone_on_ref_ptr = "warn"
cognitive_complexity = "warn"
doc_include_without_cfg = "warn"
empty_enum_variants_with_brackets = "warn"
empty_structs_with_brackets = "warn"
error_impl_error = "warn"
exit = "warn"
field_scoped_visibility_modifiers = "warn"
filetype_is_file = "warn"
float_cmp_const = "warn"
fn_to_numeric_cast_any = "warn"
infinite_loop = "warn"
lossy_float_literal = "warn"
mem_forget = "warn"
missing_assert_message = "warn"
modulo_arithmetic = "warn"
multiple_inherent_impl = "warn"
multiple_unsafe_ops_per_block = "warn"
needless_raw_strings = "warn"
non_zero_suggestions = "warn"
panic_in_result_fn = "warn"
pattern_type_mismatch = "allow"
precedence_bits = "warn"
pub_without_shorthand = "warn"
redundant_test_prefix = "warn"
ref_patterns = "warn"                      # Might cause issues with pattern_type_mismatch
renamed_function_params = "warn"
rest_pat_in_fully_bound_structs = "warn"
same_name_method = "warn"
self_named_module_files = "warn"
semicolon_outside_block = "warn"
str_to_string = "warn"
string_lit_chars_any = "warn"
string_slice = "warn"
suspicious_xor_used_as_pow = "warn"
tests_outside_test_module = "warn"
todo = "warn"
try_err = "warn"
undocumented_unsafe_blocks = "warn"
unimplemented = "warn"
unnecessary_safety_comment = "warn"
unnecessary_safety_doc = "warn"
unneeded_field_pattern = "warn"
unseparated_literal_suffix = "warn"
unused_result_ok = "warn"
unwrap_used = "warn"
wildcard_enum_match_arm = "warn"
print_stdout = "warn"
print_stderr = "warn"
